/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ComeceAgoraRouteImport } from './routes/comece-agora'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAtividadesRouteImport } from './routes/_app.atividades'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppFavoritosRouteImport } from './routes/_app.favoritos'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppIaRouteImport } from './routes/_app.ia'
import { Route as AppKpisRouteImport } from './routes/_app.kpis'
import { Route as AppNotificacoesRouteImport } from './routes/_app.notificacoes'
import { Route as AppPainelRouteImport } from './routes/_app.painel'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppPlanosRouteImport } from './routes/_app.planos'
import { Route as AppSequenciasRouteImport } from './routes/_app.sequencias'
import { Route as AppBibliotecaIndexRouteImport } from './routes/_app.biblioteca.index'
import { Route as AppBibliotecaDisciplinaRouteImport } from './routes/_app.biblioteca.$disciplina'
import { Route as AppBibliotecaDisciplinaIndexRouteImport } from './routes/_app.biblioteca.$disciplina.index'
import { Route as AppBibliotecaDisciplinaConteudoRouteImport } from './routes/_app.biblioteca.$disciplina.$conteudo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeceAgoraRoute = ComeceAgoraRouteImport.update({
  id: '/comece-agora',
  path: '/comece-agora',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAtividadesRoute = AppAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppSequenciasRoute = AppSequenciasRouteImport.update({
  id: '/sequencias',
  path: '/sequencias',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaIndexRoute = AppBibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBibliotecaRoute,
} as any)
const AppBibliotecaDisciplinaRoute = AppBibliotecaDisciplinaRouteImport.update({
  id: '/$disciplina',
  path: '/$disciplina',
  getParentRoute: () => AppBibliotecaRoute,
} as any)
const AppBibliotecaDisciplinaIndexRoute =
  AppBibliotecaDisciplinaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBibliotecaDisciplinaRoute,
  } as any)
const AppBibliotecaDisciplinaConteudoRoute =
  AppBibliotecaDisciplinaConteudoRouteImport.update({
    id: '/$conteudo',
    path: '/$conteudo',
    getParentRoute: () => AppBibliotecaDisciplinaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comece-agora': typeof ComeceAgoraRoute
  '/login': typeof LoginRoute
  '/atividades': typeof AppAtividadesRoute
  '/biblioteca': typeof AppBibliotecaRouteWithChildren
  '/favoritos': typeof AppFavoritosRoute
  '/historico': typeof AppHistoricoRoute
  '/ia': typeof AppIaRoute
  '/kpis': typeof AppKpisRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/painel': typeof AppPainelRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/sequencias': typeof AppSequenciasRoute
  '/biblioteca/$disciplina': typeof AppBibliotecaDisciplinaRouteWithChildren
  '/biblioteca/': typeof AppBibliotecaIndexRoute
  '/biblioteca/$disciplina/$conteudo': typeof AppBibliotecaDisciplinaConteudoRoute
  '/biblioteca/$disciplina/': typeof AppBibliotecaDisciplinaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comece-agora': typeof ComeceAgoraRoute
  '/login': typeof LoginRoute
  '/atividades': typeof AppAtividadesRoute
  '/favoritos': typeof AppFavoritosRoute
  '/historico': typeof AppHistoricoRoute
  '/ia': typeof AppIaRoute
  '/kpis': typeof AppKpisRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/painel': typeof AppPainelRoute
  '/perfil': typeof AppPerfilRoute
  '/planos': typeof AppPlanosRoute
  '/sequencias': typeof AppSequenciasRoute
  '/biblioteca': typeof AppBibliotecaIndexRoute
  '/biblioteca/$disciplina/$conteudo': typeof AppBibliotecaDisciplinaConteudoRoute
  '/biblioteca/$disciplina': typeof AppBibliotecaDisciplinaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/comece-agora': typeof ComeceAgoraRoute
  '/login': typeof LoginRoute
  '/_app/atividades': typeof AppAtividadesRoute
  '/_app/biblioteca': typeof AppBibliotecaRouteWithChildren
  '/_app/favoritos': typeof AppFavoritosRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/ia': typeof AppIaRoute
  '/_app/kpis': typeof AppKpisRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/sequencias': typeof AppSequenciasRoute
  '/_app/biblioteca/$disciplina': typeof AppBibliotecaDisciplinaRouteWithChildren
  '/_app/biblioteca/': typeof AppBibliotecaIndexRoute
  '/_app/biblioteca/$disciplina/$conteudo': typeof AppBibliotecaDisciplinaConteudoRoute
  '/_app/biblioteca/$disciplina/': typeof AppBibliotecaDisciplinaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comece-agora'
    | '/login'
    | '/atividades'
    | '/biblioteca'
    | '/favoritos'
    | '/historico'
    | '/ia'
    | '/kpis'
    | '/notificacoes'
    | '/painel'
    | '/perfil'
    | '/planos'
    | '/sequencias'
    | '/biblioteca/$disciplina'
    | '/biblioteca/'
    | '/biblioteca/$disciplina/$conteudo'
    | '/biblioteca/$disciplina/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comece-agora'
    | '/login'
    | '/atividades'
    | '/favoritos'
    | '/historico'
    | '/ia'
    | '/kpis'
    | '/notificacoes'
    | '/painel'
    | '/perfil'
    | '/planos'
    | '/sequencias'
    | '/biblioteca'
    | '/biblioteca/$disciplina/$conteudo'
    | '/biblioteca/$disciplina'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/comece-agora'
    | '/login'
    | '/_app/atividades'
    | '/_app/biblioteca'
    | '/_app/favoritos'
    | '/_app/historico'
    | '/_app/ia'
    | '/_app/kpis'
    | '/_app/notificacoes'
    | '/_app/painel'
    | '/_app/perfil'
    | '/_app/planos'
    | '/_app/sequencias'
    | '/_app/biblioteca/$disciplina'
    | '/_app/biblioteca/'
    | '/_app/biblioteca/$disciplina/$conteudo'
    | '/_app/biblioteca/$disciplina/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ComeceAgoraRoute: typeof ComeceAgoraRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comece-agora': {
      id: '/comece-agora'
      path: '/comece-agora'
      fullPath: '/comece-agora'
      preLoaderRoute: typeof ComeceAgoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/atividades': {
      id: '/_app/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AppAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoritos': {
      id: '/_app/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpis': {
      id: '/_app/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sequencias': {
      id: '/_app/sequencias'
      path: '/sequencias'
      fullPath: '/sequencias'
      preLoaderRoute: typeof AppSequenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca/': {
      id: '/_app/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof AppBibliotecaIndexRouteImport
      parentRoute: typeof AppBibliotecaRoute
    }
    '/_app/biblioteca/$disciplina': {
      id: '/_app/biblioteca/$disciplina'
      path: '/$disciplina'
      fullPath: '/biblioteca/$disciplina'
      preLoaderRoute: typeof AppBibliotecaDisciplinaRouteImport
      parentRoute: typeof AppBibliotecaRoute
    }
    '/_app/biblioteca/$disciplina/': {
      id: '/_app/biblioteca/$disciplina/'
      path: '/'
      fullPath: '/biblioteca/$disciplina/'
      preLoaderRoute: typeof AppBibliotecaDisciplinaIndexRouteImport
      parentRoute: typeof AppBibliotecaDisciplinaRoute
    }
    '/_app/biblioteca/$disciplina/$conteudo': {
      id: '/_app/biblioteca/$disciplina/$conteudo'
      path: '/$conteudo'
      fullPath: '/biblioteca/$disciplina/$conteudo'
      preLoaderRoute: typeof AppBibliotecaDisciplinaConteudoRouteImport
      parentRoute: typeof AppBibliotecaDisciplinaRoute
    }
  }
}

interface AppBibliotecaDisciplinaRouteChildren {
  AppBibliotecaDisciplinaConteudoRoute: typeof AppBibliotecaDisciplinaConteudoRoute
  AppBibliotecaDisciplinaIndexRoute: typeof AppBibliotecaDisciplinaIndexRoute
}

const AppBibliotecaDisciplinaRouteChildren: AppBibliotecaDisciplinaRouteChildren =
  {
    AppBibliotecaDisciplinaConteudoRoute: AppBibliotecaDisciplinaConteudoRoute,
    AppBibliotecaDisciplinaIndexRoute: AppBibliotecaDisciplinaIndexRoute,
  }

const AppBibliotecaDisciplinaRouteWithChildren =
  AppBibliotecaDisciplinaRoute._addFileChildren(
    AppBibliotecaDisciplinaRouteChildren,
  )

interface AppBibliotecaRouteChildren {
  AppBibliotecaDisciplinaRoute: typeof AppBibliotecaDisciplinaRouteWithChildren
  AppBibliotecaIndexRoute: typeof AppBibliotecaIndexRoute
}

const AppBibliotecaRouteChildren: AppBibliotecaRouteChildren = {
  AppBibliotecaDisciplinaRoute: AppBibliotecaDisciplinaRouteWithChildren,
  AppBibliotecaIndexRoute: AppBibliotecaIndexRoute,
}

const AppBibliotecaRouteWithChildren = AppBibliotecaRoute._addFileChildren(
  AppBibliotecaRouteChildren,
)

interface AppRouteChildren {
  AppAtividadesRoute: typeof AppAtividadesRoute
  AppBibliotecaRoute: typeof AppBibliotecaRouteWithChildren
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppIaRoute: typeof AppIaRoute
  AppKpisRoute: typeof AppKpisRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPainelRoute: typeof AppPainelRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppSequenciasRoute: typeof AppSequenciasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtividadesRoute: AppAtividadesRoute,
  AppBibliotecaRoute: AppBibliotecaRouteWithChildren,
  AppFavoritosRoute: AppFavoritosRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppIaRoute: AppIaRoute,
  AppKpisRoute: AppKpisRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPainelRoute: AppPainelRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppSequenciasRoute: AppSequenciasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ComeceAgoraRoute: ComeceAgoraRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
